server:
  port: 8083

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  # ✅ REDIS CONFIG (for rate limiter)
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

            # ✅ RATE LIMITER ENABLED
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2     # 2 requests per second
                redis-rate-limiter.burstCapacity: 2     # max 4 requests at once
                key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
